version: "3"

services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    container_name: ${APP_NAME}-nginx
    ports:
      - "${APP_WEB_PORT}:80"
    volumes:
      - ./:${APP_PATH}
    depends_on:
      - php

  php:
    build:
      args:
        user: ${DOCKER_USER}
        uid: 1000
      context: .
      dockerfile: ./docker/php/Dockerfile
    image: atrem2023/otus-docker:amd64
    volumes:
      - ./:${APP_PATH}
    depends_on:
      - db
    container_name: ${APP_NAME}_php

  db:
    image: postgres
    container_name: ${APP_NAME}_db
    volumes:
      - ./tmp/postgresql/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'

  pgAdmin:
    image: dpage/pgadmin4
    container_name: ${APP_NAME}_pgAdmin
    ports:
      - "5050:80"
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: '${APP_MAIL_ADDRESS}'
      PGADMIN_DEFAULT_PASSWORD: '${DB_PASSWORD}'

  redis:
    container_name: ${APP_NAME}-redis
    image: redis:7.0.11-alpine
    volumes:
      - ./docker/volumes/redis:/data
    ports:
      - "${APP_REDIS_PORT}:6379"

  npm:
    build:
      context: .
      dockerfile: /docker/node/Dockerfile
    container_name: ${APP_NAME}-npm
    volumes:
      - ./:${APP_PATH}:cached
      - ./.env:${APP_PATH}/.env
    working_dir: ${APP_PATH}
    profiles: [ "npm" ]
    entrypoint: [ 'npm' ]
    ports:
      - "${VITE_PORT}:${VITE_PORT}"